name: OzkanGMI APK Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_display_name: OzkanGMI

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: OzkanGMI-Package
          path: bin/*.apk
          
