name: Ozkan_Build_Final_v1

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04 # En hızlı ve uyumlu sürüm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          sudo pip3 install --upgrade pip
          sudo pip3 install buildozer cython==0.29.33 kivy

      - name: Build APK
        run: |
          yes | buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "True"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Ozkan-APK
          path: bin/*.apk
          
