name: OzkanGMI APK Build

on:
  workflow_dispatch: # Manuel başlatma düğmesi ekler
  push:
    branches: [ main ] # Ana kola kod yükleyince çalışır
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-level: '3.9'

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_display_name: OzkanGMI

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: OzkanGMI-Paketim
          path: bin/*.apk
          
